In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## LOAD DATA

In [4]:
df = pd.read_csv(r"D:\Downloads\Data_Entry_2017.csv")
df

,Image Index,Finding Labels,Follow-up #,Patient ID,Patient Age,Patient Gender,View Position,OriginalImage[Width,Height],OriginalImagePixelSpacing[x,y],Unnamed: 11
0,00000001_000.png,Cardiomegaly,0,1,58,M,PA,2682,2749,0.143,0.143,NaN
1,00000001_001.png,Cardiomegaly|Emphysema,1,1,58,M,PA,2894,2729,0.143,0.143,NaN
2,00000001_002.png,Cardiomegaly|Effusion,2,1,58,M,PA,2500,2048,0.168,0.168,NaN
3,00000002_000.png,No Finding,0,2,81,M,PA,2500,2048,0.171,0.171,NaN
4,00000003_000.png,Hernia,0,3,81,F,PA,2582,2991,0.143,0.143,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
112115,00030801_001.png,Mass|Pneumonia,1,30801,39,M,PA,2048,2500,0.168,0.168,NaN
112116,00030802_000.png,No Finding,0,30802,29,M,PA,2048,2500,0.168,0.168,NaN
112117,00030803_000.png,No Finding,0,30803,42,F,PA,2048,2500,0.168,0.168,NaN
112118,00030804_000.png,No Finding,0,30804,30,F,PA,2048,2500,0.168,0.168,NaN
112119,00030805_000.png,No Finding,0,30805,27,M,PA,2048,2500,0.171,0.171,NaN

## Inspection

In [5]:
df.head(10)

,Image Index,Finding Labels,Follow-up #,Patient ID,Patient Age,Patient Gender,View Position,OriginalImage[Width,Height],OriginalImagePixelSpacing[x,y],Unnamed: 11
0,00000001_000.png,Cardiomegaly,0,1,58,M,PA,2682,2749,0.143,0.143,NaN
1,00000001_001.png,Cardiomegaly|Emphysema,1,1,58,M,PA,2894,2729,0.143,0.143,NaN
2,00000001_002.png,Cardiomegaly|Effusion,2,1,58,M,PA,2500,2048,0.168,0.168,NaN
3,00000002_000.png,No Finding,0,2,81,M,PA,2500,2048,0.171,0.171,NaN
4,00000003_000.png,Hernia,0,3,81,F,PA,2582,2991,0.143,0.143,NaN
5,00000003_001.png,Hernia,1,3,74,F,PA,2500,2048,0.168,0.168,NaN
6,00000003_002.png,Hernia,2,3,75,F,PA,2048,2500,0.168,0.168,NaN
7,00000003_003.png,Hernia|Infiltration,3,3,76,F,PA,2698,2991,0.143,0.143,NaN
8,00000003_004.png,Hernia,4,3,77,F,PA,2500,2048,0.168,0.168,NaN
9,00000003_005.png,Hernia,5,3,78,F,PA,2686,2991,0.143,0.143,NaN

In [7]:
df.shape

(112120, 12)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112120 entries, 0 to 112119
Data columns (total 12 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Image Index                  112120 non-null  object
 1   Finding Labels               112120 non-null  object
 2   Follow-up #                  112120 non-null  int64
 3   Patient ID                   112120 non-null  int64
 4   Patient Age                  112120 non-null  int64
 5   Patient Gender               112120 non-null  object
 6   View Position                112120 non-null  object
 7   OriginalImage[Width          112120 non-null  int64
 8   Height]                      112120 non-null  int64
 9   OriginalImagePixelSpacing[x  112120 non-null  float64
 10  y]                           112120 non-null  float64
 11  Unnamed: 11                  0 non-null       float64
dtypes: float64(3), int64(5), object(4)
memory usage: 10.3+ MB

In [9]:
df.describe(include="all")

,Image Index,Finding Labels,Follow-up #,Patient ID,Patient Age,Patient Gender,View Position,OriginalImage[Width,Height],OriginalImagePixelSpacing[x,y],Unnamed: 11
count,112120,112120,112120.000000,112120.000000,112120.000000,112120,112120,112120.000000,112120.000000,112120.000000,112120.000000,0.0
unique,112120,836,NaN,NaN,NaN,2,2,NaN,NaN,NaN,NaN,NaN
top,00030805_000.png,No Finding,NaN,NaN,NaN,M,PA,NaN,NaN,NaN,NaN,NaN
freq,1,60361,NaN,NaN,NaN,63340,67310,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,8.573751,14346.381743,46.901463,NaN,NaN,2646.078844,2486.438842,0.155649,0.155649,NaN
std,NaN,NaN,15.406320,8403.876972,16.839923,NaN,NaN,341.246429,401.268227,0.016174,0.016174,NaN
min,NaN,NaN,0.000000,1.000000,1.000000,NaN,NaN,1143.000000,966.000000,0.115000,0.115000,NaN
25%,NaN,NaN,0.000000,7310.750000,35.000000,NaN,NaN,2500.000000,2048.000000,0.143000,0.143000,NaN
50%,NaN,NaN,3.000000,13993.000000,49.000000,NaN,NaN,2518.000000,2544.000000,0.143000,0.143000,NaN
75%,NaN,NaN,10.000000,20673.000000,59.000000,NaN,NaN,2992.000000,2991.000000,0.168000,0.168000,NaN
max,NaN,NaN,183.000000,30805.000000,414.000000,NaN,NaN,3827.000000,4715.000000,0.198800,0.198800,NaN

In [10]:
df.isnull().sum()

Image Index                         0
Finding Labels                      0
Follow-up #                         0
Patient ID                          0
Patient Age                         0
Patient Gender                      0
View Position                       0
OriginalImage[Width                 0
Height]                             0
OriginalImagePixelSpacing[x         0
y]                                  0
Unnamed: 11                    112120
dtype: int64

In [11]:
missing = (df.isnull().sum().to_frame("missing_count"))

missing["missing_percentage"] = (
    missing["missing_count"] / len(df) * 100
)

missing

                             missing_count  missing_percentage
Image Index                              0                 0.0
Finding Labels                           0                 0.0
Follow-up #                              0                 0.0
Patient ID                               0                 0.0
Patient Age                              0                 0.0
Patient Gender                           0                 0.0
View Position                            0                 0.0
OriginalImage[Width                      0                 0.0
Height]                                  0                 0.0
OriginalImagePixelSpacing[x              0                 0.0
y]                                       0                 0.0
Unnamed: 11                         112120               100.0

In [ ]:
df.drop('Unnamed: 11', inplace=True, axis=1)

## RENAME COLUMNS

In [15]:
df = df.rename(columns={
    "Image Index": "image_id",
    "Finding Labels": "finding_labels",
    "Follow-up #": "follow_up",
    "Patient ID": "patient_id",
    "Patient Age": "patient_age",
    "Patient Gender": "patient_gender",
    "View Position": "view_position",
    "OriginalImage[Width": "image_width",
    "Height]": "image_height",
    "OriginalImagePixelSpacing[x": "pixel_spacing_x",
    "y]": "pixel_spacing_y"
})

In [16]:
df.columns

Index(['image_id', 'finding_labels', 'follow_up', 'patient_id', 'patient_age',
       'patient_gender', 'view_position', 'image_width', 'image_height',
       'pixel_spacing_x', 'pixel_spacing_y'],
      dtype='object')

## Check DUPLICATES

In [17]:
df.duplicated().sum()

np.int64(0)

In [19]:
df["patient_id"].nunique()

30805

In [49]:
df["image_id"].duplicated().sum()

np.int64(0)

In [50]:
df["image_id"].nunique()

112120

## Age CLEANING

In [25]:
df.loc[(df["patient_age"] < 0) | (df["patient_age"] > 100)]

,image_id,finding_labels,follow_up,patient_id,patient_age,patient_gender,view_position,image_width,image_height,pixel_spacing_x,pixel_spacing_y
20852,00005567_000.png,Effusion|Pneumonia,0,5567,412,M,AP,3056,2544,0.139,0.139
46965,00011973_002.png,Edema,2,11973,414,M,AP,3056,2544,0.139,0.139
48284,00012238_010.png,No Finding,10,12238,148,M,PA,2992,2991,0.143,0.143
55742,00013950_000.png,No Finding,0,13950,148,M,PA,2964,2939,0.143,0.143
58650,00014520_026.png,Infiltration|Mass,26,14520,150,M,PA,2992,2991,0.143,0.143
62929,00015558_000.png,No Finding,0,15558,149,M,PA,2992,2991,0.143,0.143
74884,00018366_044.png,Pneumothorax,44,18366,152,F,PA,2302,2991,0.143,0.143
78795,00019346_000.png,Infiltration,0,19346,151,F,PA,2678,2774,0.143,0.143
84810,00020900_002.png,No Finding,2,20900,411,M,AP,3056,2544,0.139,0.139
85404,00021047_002.png,Mass|Pleural_Thickening,2,21047,412,M,AP,3056,2544,0.139,0.139
86264,00021275_003.png,No Finding,3,21275,413,F,AP,3056,2544,0.139,0.139
91369,00022811_000.png,No Finding,0,22811,412,M,PA,3056,2544,0.139,0.139
95794,00025206_000.png,Infiltration|Mass,0,25206,153,M,PA,2992,2991,0.143,0.143
98495,00026028_001.png,Atelectasis,1,26028,154,M,PA,2992,2991,0.143,0.143
101194,00026871_000.png,No Finding,0,26871,155,F,PA,2992,2991,0.143,0.143
104590,00027989_000.png,No Finding,0,27989,155,M,PA,2992,2991,0.143,0.143

In [26]:
((df["patient_age"] < 0) | (df["patient_age"] > 100)).sum()

np.int64(16)

In [27]:
df.loc[(df["patient_age"] < 0) | (df["patient_age"] > 100), "patient_age"] = np.nan

df["patient_age"] = df["patient_age"].fillna(
    df.groupby("patient_gender")["patient_age"].transform("median")
)

In [28]:
((df["patient_age"] < 0) | (df["patient_age"] > 100)).sum()

np.int64(0)

In [40]:
df["patient_age"] = df["patient_age"].astype(int)

print(df["patient_age"].dtype)

int64

## Gender

In [29]:
df["patient_gender"].value_counts(dropna=False)

patient_gender
M    63340
F    48780
Name: count, dtype: int64

## View Position

In [30]:
df["view_position"].value_counts(dropna=False)

view_position
PA    67310
AP    44810
Name: count, dtype: int64

## Follow-up

In [54]:
df["follow_up"].describe()

count    112120.000000
mean          8.573751
std          15.406320
min           0.000000
25%           0.000000
50%           3.000000
75%          10.000000
max         183.000000
Name: follow_up, dtype: float64

In [55]:
df["follow_up"].value_counts().sort_index().head(20)

follow_up
0     30805
1     13302
2      9189
3      7089
4      5759
5      4821
6      4034
7      3426
8      2932
9      2545
10     2225
11     1944
12     1709
13     1544
14     1363
15     1242
16     1122
17     1031
18      954
19      877
Name: count, dtype: int64

In [56]:
df.groupby("patient_id")["follow_up"].max().describe()

count    30805.000000
mean         2.639669
std          7.266734
min          0.000000
25%          0.000000
50%          0.000000
75%          2.000000
max        183.000000
Name: follow_up, dtype: float64

In [57]:
df[
    ["patient_id", "follow_up", "image_id", "patient_age"]
].sort_values(
    ["patient_id", "follow_up"]
).head(30)

    patient_id  follow_up          image_id  patient_age
0            1          0  00000001_000.png           58
1            1          1  00000001_001.png           58
2            1          2  00000001_002.png           58
3            2          0  00000002_000.png           81
4            3          0  00000003_000.png           81
5            3          1  00000003_001.png           74
6            3          2  00000003_002.png           75
7            3          3  00000003_003.png           76
8            3          4  00000003_004.png           77
9            3          5  00000003_005.png           78
10           3          6  00000003_006.png           79
11           3          7  00000003_007.png           80
12           4          0  00000004_000.png           82
13           5          0  00000005_000.png           69
14           5          1  00000005_001.png           69
15           5          2  00000005_002.png           69
16           5          3  00000005_003.png           69
17           5          4  00000005_004.png           70
18           5          5  00000005_005.png           70
19           5          6  00000005_006.png           70
20           5          7  00000005_007.png           70
21           6          0  00000006_000.png           81
22           7          0  00000007_000.png           82
23           8          0  00000008_000.png           69
24           8          1  00000008_001.png           70
25           8          2  00000008_002.png           73
26           9          0  00000009_000.png           73
27          10          0  00000010_000.png           84
28          11          0  00000011_000.png           75
29          11          1  00000011_001.png           75

## Categorical Features

In [ ]:
df["patient_gender"] = df["patient_gender"].astype("category")
df["view_position"] = df["view_position"].astype("category")

category

## Finding Labels

In [36]:
labels = df["finding_labels"].str.split("|").explode()

labels.value_counts()

finding_labels
No Finding            60361
Infiltration          19894
Effusion              13317
Atelectasis           11559
Nodule                 6331
Mass                   5782
Pneumothorax           5302
Consolidation          4667
Pleural_Thickening     3385
Cardiomegaly           2776
Emphysema              2516
Edema                  2303
Fibrosis               1686
Pneumonia              1431
Hernia                  227
Name: count, dtype: int64

In [58]:
unique_labels = sorted(labels.unique())

print("Number of unique labels:", len(unique_labels))
print(unique_labels)

Number of unique labels: 15
['Atelectasis', 'Cardiomegaly', 'Consolidation', 'Edema', 'Effusion', 'Emphysema', 'Fibrosis', 'Hernia', 'Infiltration', 'Mass', 'No Finding', 'Nodule', 'Pleural_Thickening', 'Pneumonia', 'Pneumothorax']

In [59]:
no_finding_mixed = df[
    df["finding_labels"].str.contains(
        "No Finding",
        na=False
    ) &
    df["finding_labels"].str.contains(
        r"\|",
        regex=True,
        na=False
    )
]

len(no_finding_mixed)

0

In [44]:
df["num_diseases"] = df["finding_labels"].str.count(r"\|") + 1

df["num_diseases"].value_counts().sort_index()

num_diseases
1    91324
2    14306
3     4856
4     1247
5      301
6       67
7       16
8        1
9        2
Name: count, dtype: int64

In [45]:
unique_labels = set(labels.unique())

for label in unique_labels:
    if label != "No Finding":
        df[label] = df["finding_labels"].apply(lambda x: 1 if label in x.split("|") else 0)

df["has_finding"] = (df["finding_labels"] != "No Finding").astype(int)

In [46]:
df

,image_id,finding_labels,follow_up,patient_id,patient_age,patient_gender,view_position,image_width,image_height,pixel_spacing_x,...,Atelectasis,Emphysema,Pneumothorax,Fibrosis,Edema,Nodule,Consolidation,Pneumonia,Pleural_Thickening,has_finding
0,00000001_000.png,Cardiomegaly,0,1,58,M,PA,2682,2749,0.143,...,0,0,0,0,0,0,0,0,0,1
1,00000001_001.png,Cardiomegaly|Emphysema,1,1,58,M,PA,2894,2729,0.143,...,0,1,0,0,0,0,0,0,0,1
2,00000001_002.png,Cardiomegaly|Effusion,2,1,58,M,PA,2500,2048,0.168,...,0,0,0,0,0,0,0,0,0,1
3,00000002_000.png,No Finding,0,2,81,M,PA,2500,2048,0.171,...,0,0,0,0,0,0,0,0,0,0
4,00000003_000.png,Hernia,0,3,81,F,PA,2582,2991,0.143,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112115,00030801_001.png,Mass|Pneumonia,1,30801,39,M,PA,2048,2500,0.168,...,0,0,0,0,0,0,0,1,0,1
112116,00030802_000.png,No Finding,0,30802,29,M,PA,2048,2500,0.168,...,0,0,0,0,0,0,0,0,0,0
112117,00030803_000.png,No Finding,0,30803,42,F,PA,2048,2500,0.168,...,0,0,0,0,0,0,0,0,0,0
112118,00030804_000.png,No Finding,0,30804,30,F,PA,2048,2500,0.168,...,0,0,0,0,0,0,0,0,0,0
112119,00030805_000.png,No Finding,0,30805,27,M,PA,2048,2500,0.171,...,0,0,0,0,0,0,0,0,0,0

## Image Metadata Sanity Check

In [47]:
invalid_dimensions = df[
    (df["image_width"] <= 0) | 
    (df["image_height"] <= 0) | 
    (df["pixel_spacing_x"] <= 0) | 
    (df["pixel_spacing_y"] <= 0)
]

len(invalid_dimensions)

0

In [61]:
(
    df["pixel_spacing_x"] ==
    df["pixel_spacing_y"]
).value_counts()

True    112120
Name: count, dtype: int64

## Patient metadata consistency

In [51]:
gender_consistency = (
    df.groupby("patient_id")["patient_gender"]
    .nunique()
)

gender_consistency.value_counts()

patient_gender
1    30805
Name: count, dtype: int64

In [52]:
age_stats = (
    df.groupby("patient_id")["patient_age"]
    .agg(["min", "max", "nunique"])
)

age_stats.sort_values(
    "nunique",
    ascending=False
).head(20)

            min  max  nunique
patient_id
2524         49   63       13
621          63   76       13
5067         49   61       13
1093         64   77       13
3709         48   61       13
3527         47   59       12
1718         68   80       12
2649         52   63       12
5532         30   42       12
4822         24   35       12
3989         53   65       11
3574         49   61       11
623          51   63       11
6875         52   64       11
23498        54   65       11
6192         34   45       11
1367         62   73       11
2825         60   71       11
2547         51   64       11
3659         47   60       11

In [62]:
images_per_patient = (
    df.groupby("patient_id")
    .size()
)

images_per_patient.describe()

count    30805.000000
mean         3.639669
std          7.266734
min          1.000000
25%          1.000000
50%          1.000000
75%          3.000000
max        184.000000
dtype: float64

In [63]:
images_per_patient.sort_values(
    ascending=False
).head(20)

patient_id
10007    184
13670    173
15530    158
12834    157
13993    143
1836     137
19124    130
20213    119
17138    117
11237    116
13111    116
21201    114
17236    111
20326    109
19176    108
14022    108
6271     108
4808     102
16587     99
18253     91
dtype: int64

In [64]:
quality_report = pd.DataFrame({
    "metric": [
        "Number of rows",
        "Number of columns",
        "Unique images",
        "Unique patients",
        "Missing values",
        "Duplicate rows",
        "Invalid ages",
        "Invalid dimensions",
        "Unique findings",
        "PA images",
        "AP images"
    ],
    
    "value": [
        len(df),
        df.shape[1],
        df["image_id"].nunique(),
        df["patient_id"].nunique(),
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        (
            (df["patient_age"] < 0) |
            (df["patient_age"] > 100)
        ).sum(),
        len(invalid_dimensions),
        df["finding_labels"].nunique(),
        (df["view_position"] == "PA").sum(),
        (df["view_position"] == "AP").sum()
    ]
})

quality_report

                metric   value
0       Number of rows  112120
1    Number of columns      28
2        Unique images  112120
3      Unique patients   30805
4       Missing values       0
5       Duplicate rows       0
6         Invalid ages       0
7   Invalid dimensions       0
8      Unique findings     836
9            PA images   67310
10           AP images   44810

## Export Cleaned Data

In [48]:
df.reset_index(drop=True, inplace=True)

print(df.info())
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112120 entries, 0 to 112119
Data columns (total 28 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   image_id            112120 non-null  object
 1   finding_labels      112120 non-null  object
 2   follow_up           112120 non-null  int64
 3   patient_id          112120 non-null  int64
 4   patient_age         112120 non-null  int64
 5   patient_gender      112120 non-null  category
 6   view_position       112120 non-null  category
 7   image_width         112120 non-null  int64
 8   image_height        112120 non-null  int64
 9   pixel_spacing_x     112120 non-null  float64
 10  pixel_spacing_y     112120 non-null  float64
 11  num_labels          112120 non-null  int64
 12  num_diseases        112120 non-null  int64
 13  Hernia              112120 non-null  int64
 14  Infiltration        112120 non-null  int64
 15  Mass                112120 non-null  int64
 16  Cardiomegaly        112120 non-null  int64
 17  Effusion            112120 non-null  int64
 18  Atelectasis         112120 non-null  int64
 19  Emphysema           112120 non-null  int64
 20  Pneumothorax        112120 non-null  int64
 21  Fibrosis            112120 non-null  int64
 22  Edema               112120 non-null  int64
 23  Nodule              112120 non-null  int64
 24  Consolidation       112120 non-null  int64
 25  Pneumonia           112120 non-null  int64
 26  Pleural_Thickening  112120 non-null  int64
 27  has_finding         112120 non-null  int64
dtypes: category(2), float64(2), int64(22), object(2)
memory usage: 22.5+ MB
None

,image_id,finding_labels,follow_up,patient_id,patient_age,patient_gender,view_position,image_width,image_height,pixel_spacing_x,...,Atelectasis,Emphysema,Pneumothorax,Fibrosis,Edema,Nodule,Consolidation,Pneumonia,Pleural_Thickening,has_finding
0,00000001_000.png,Cardiomegaly,0,1,58,M,PA,2682,2749,0.143,...,0,0,0,0,0,0,0,0,0,1
1,00000001_001.png,Cardiomegaly|Emphysema,1,1,58,M,PA,2894,2729,0.143,...,0,1,0,0,0,0,0,0,0,1
2,00000001_002.png,Cardiomegaly|Effusion,2,1,58,M,PA,2500,2048,0.168,...,0,0,0,0,0,0,0,0,0,1
3,00000002_000.png,No Finding,0,2,81,M,PA,2500,2048,0.171,...,0,0,0,0,0,0,0,0,0,0
4,00000003_000.png,Hernia,0,3,81,F,PA,2582,2991,0.143,...,0,0,0,0,0,0,0,0,0,1

In [65]:
df.to_csv(r"D:\Downloads\Data_Entry_2017_Cleaned.csv", index=False)